var gulp = require('gulp');
var usemin = require('gulp-usemin');
var uglify = require('gulp-uglify');
var minifyCss = require('gulp-minify-css');
var rename = require('gulp-rename');
var rimraf = require('gulp-rimraf');
var replace = require('gulp-replace');
var header = require('gulp-header');

gulp.task('minify', function(){
  return gulp.src('templates/layout.src.tpl')
        .pipe(usemin({
          assetsDir: 'templates',
          css: [minifyCss(), 'concat'],
          js: [uglify(), 'concat']
        }))
        .pipe(gulp.dest('templates'));
});

gulp.task('fix-template', ['minify'], function(){
  return gulp.src('templates/layout.src.tpl')
               .pipe(rimraf())
               .pipe(rename('layout.tpl')) 
               .pipe(gulp.dest('src/templates'));
});

gulp.task('fix-paths', ['minify'], function(){
  gulp.src('src/css/site.css')
        .pipe(replace('../', '../../bower_components/bootstrap/dist/'))
        .pipe(gulp.dest('src/css'));
});

gulp.task('add-headers', ['fix-template'], function(){
  gulp.src('src/templates/layout.tpl')
        .pipe(header("<!-- This file is generated by machine - do not edit! You've been warned. -->\n"))
        .pipe(gulp.dest('src/templates'));

  gulp.src('src/js/site.js')
        .pipe(header("<!-- This file is generated by machine - do not edit! You've been warned. -->\n"))
        .pipe(gulp.dest('src/js/'));

  gulp.src('src/css/site.css')
        .pipe(header("<!-- This file is generated by machine - do not edit! You've been warned. -->\n"))
        .pipe(gulp.dest('src/css'));
});

gulp.task('clean', function(){
  var generated = ['src/css/site.css', 'src/js/site.js', 'src/template/layout.tpl'];
  return gulp.src(generated)
               .pipe(rimraf());
});

gulp.task('dev', ['clean'], function(){
  gulp.src('src/templates/layout.src.tpl')
        .pipe(rename('layout.tpl'))
        .pipe(gulp.dest('src/templates'));

  gulp.src('bower_components/bootstrap/dist/css/bootstrap.min.css')
        .pipe(gulp.dest('src/css'));

  gulp.src('bower_components/bootstrap/dist/js/bootstrap.min.js')
        .pipe(gulp.dest('src/js'));

  gulp.src('bower_components/jquery/dist/jquery.min.js')
        .pipe(gulp.dest('src/js'));

});
gulp.task('default', ['minify', 'fix-template', 'fix-paths', 'add-headers']);
